# Generated by Django 5.1.1 on 2024-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('clarendon', 'Clarendon'), ('gingham', 'Gingham'), ('moon', 'Moon'), ('reyes', 'Reyes'), ('perpetua', 'Perpetua'), ('amaro', 'Amaro'), ('mayfair', 'Mayfair'), ('willow', 'Willow'), ('juno', 'Juno'), ('slumber', 'Slumber'), ('crema', 'Crema'), ('ludwig', 'Ludwig'), ('aden', 'Aden'), ('brooklyn', 'Brooklyn')], default='normal', max_length=32),
        ),
    ]
